package com.roplant.sep.service;

import com.roplant.sep.model.BaseUser;
import com.roplant.sep.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class AuthService {

    @Autowired
    private RepresentativeRepository repRepo;
    @Autowired
    private ProductionManagerRepository prodManRepo;
    @Autowired
    private StockManagerRepository stockManRepo;
    @Autowired
    private CustomerRepository customerRepo;
    @Autowired
    private VendorRepository vendorRepo;
    @Autowired
    private LabourWorkerRepository labourRepo;

    public BaseUser login(String cnic, String password, String role) {
        BaseUser user = null;

        // Simple switch case to check role-specific tables
        switch (role.toUpperCase()) {
            case "REPRESENTATIVE":
                user = repRepo.findByCnic(cnic);
                break;
            case "PRODUCTION_MANAGER":
                user = prodManRepo.findAll().stream()
                        .filter(u -> u.getCnic().equals(cnic)).findFirst().orElse(null);
                break;
            case "STOCK_MANAGER":
                user = stockManRepo.findAll().stream()
                        .filter(u -> u.getCnic().equals(cnic)).findFirst().orElse(null);
                break;
            case "CUSTOMER":
                user = customerRepo.findAll().stream()
                        .filter(u -> u.getCnic().equals(cnic)).findFirst().orElse(null);
                break;
            case "VENDOR":
                user = vendorRepo.findAll().stream()
                        .filter(u -> u.getCnic().equals(cnic)).findFirst().orElse(null);
                break;
            case "LABOUR_WORKER":
                user = labourRepo.findAll().stream()
                        .filter(u -> u.getCnic().equals(cnic)).findFirst().orElse(null);
                break;
            default:
                throw new RuntimeException("Invalid Role");
        }

        if (user != null && user.getPassword().equals(password)) {
            return user;
        }
        return null;
    }

    public BaseUser register(java.util.Map<String, String> payload) {
        String roleStr = payload.get("role");
        String cnic = payload.get("cnic");

        if (roleStr == null || cnic == null)
            throw new RuntimeException("Role and CNIC are required");

        com.roplant.sep.enums.Role roleEnum;
        try {
            // Handle mapping of input "LABOUR_WORKER" to enum "LABOUR" if necessary, or
            // just expect 'LABOUR'
            if ("LABOUR_WORKER".equalsIgnoreCase(roleStr)) {
                roleEnum = com.roplant.sep.enums.Role.LABOUR;
            } else {
                roleEnum = com.roplant.sep.enums.Role.valueOf(roleStr.toUpperCase());
            }
        } catch (IllegalArgumentException e) {
            throw new RuntimeException("Invalid Role: " + roleStr);
        }

        switch (roleEnum) {
            case REPRESENTATIVE:
                com.roplant.sep.model.Representative rep = new com.roplant.sep.model.Representative();
                populateBaseUser(rep, payload, roleEnum);
                // ID is generated by JPA
                rep.setNtn(payload.getOrDefault("ntn", "N/A"));
                rep.setAuthorizationLevel(payload.getOrDefault("authorizationLevel", "LOW"));
                rep.setRepresentativeBalance(
                        new java.math.BigDecimal(payload.getOrDefault("representativeBalance", "0.0")));
                return repRepo.save(rep);

            case PRODUCTION_MANAGER:
                com.roplant.sep.model.ProductionManager pm = new com.roplant.sep.model.ProductionManager();
                populateBaseUser(pm, payload, roleEnum);
                // ID is generated by JPA
                pm.setNtn(payload.getOrDefault("ntn", "N/A"));
                pm.seteLink(payload.getOrDefault("eLink", "")); // Corrected method name
                pm.setStatus("ACTIVE");
                pm.setAuthorizationLevel(payload.getOrDefault("authorizationLevel", "HIGH"));
                return prodManRepo.save(pm);

            case STOCK_MANAGER:
                com.roplant.sep.model.StockManager sm = new com.roplant.sep.model.StockManager();
                populateBaseUser(sm, payload, roleEnum);
                // ID is generated by JPA
                sm.setAuthorizationLevel(payload.getOrDefault("authorizationLevel", "MEDIUM"));
                sm.setVendorBalance(java.math.BigDecimal.ZERO); // Initial
                return stockManRepo.save(sm);

            case CUSTOMER:
                com.roplant.sep.model.Customer cust = new com.roplant.sep.model.Customer();
                populateBaseUser(cust, payload, roleEnum);
                // ID is generated by JPA
                cust.setStatus("ACTIVE");
                cust.setCustomerBalance(java.math.BigDecimal.ZERO);
                cust.setClientImagePath(payload.getOrDefault("clientImagePath", ""));
                return customerRepo.save(cust);

            case VENDOR:
                com.roplant.sep.model.Vendor ven = new com.roplant.sep.model.Vendor();
                populateBaseUser(ven, payload, roleEnum);
                // ID is generated by JPA
                ven.setVendorBalance(java.math.BigDecimal.ZERO);
                return vendorRepo.save(ven);

            case LABOUR:
                com.roplant.sep.model.LabourWorker lab = new com.roplant.sep.model.LabourWorker();
                populateBaseUser(lab, payload, roleEnum);
                // ID is generated by JPA
                lab.setAuthorizationLevel("LOW");
                lab.setLabourBalance(java.math.BigDecimal.ZERO);
                return labourRepo.save(lab);

            default:
                throw new RuntimeException("Registration not supported for role: " + roleEnum);
        }
    }

    private void populateBaseUser(BaseUser user, java.util.Map<String, String> payload,
            com.roplant.sep.enums.Role role) {
        user.setName(payload.get("name"));
        user.setAddress(payload.get("address"));
        user.setPhoneNo(payload.get("phoneNo"));
        user.setCnic(payload.get("cnic"));
        user.setPassword(payload.get("password"));
        user.setRole(role);
        user.setAboutMe(payload.getOrDefault("aboutMe", ""));

        user.setStartDate(java.time.LocalDate.now());
        user.setEndDate(null);
    }
}